# Only run on new tags
on:
  push:
    branches: "*"
    tags: "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Run tests
        run: |
          pip install poetry
          poetry install
          poetry run pytest

  publish:
    needs: tests
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Publish to PyPI
        run: |
          pip install poetry
          poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN }}
